### ISSUE TITLE
The OE recipe for libparodus in meta-rdk is not building the latest upstream version

### ISSUE THREAD

**Issue by armcc** [Comcast/libparodus#24]
The OE recipe for libparodus in meta-rdk currently sets SRCREV = "9b33e01...", which is many revisions behind the latest version.

**Comment by kraj** [comment]
@schmidtw please plan updating yocto recipe to bump to latest libaparodus. There are fixes here which we need for Yocto 2.2/RDKB migration

**Comment by kraj** [comment]
Thanks @shilpa24balaji please close this ticket after its merged into yocto

**Comment by shilpa24balaji** [comment]
@armcc I am not able to open https://code.rdkcentral.com/r/#/c/12742/
I have raised review https://gerrit.teamccp.com/146844 to remove LDFLAG from libparodus recipe file

**Comment by shilpa24balaji** [comment]
@armcc Can I close this issue, now that the removal of LDFLAG change is merged in yocto master for libparodus?

**Comment by armcc** [comment]
The LDFLAG change arrived in CMF today. Looks good. Issue can be closed.
